v1
CREATE TABLE USER_TYPES(
    id INT AUTO_INCREMENT NOT NULL,
    name VARCHAR(5) NOT NULL,
    CONSTRAINT PK_USER_TYPES PRIMARY KEY (id)
);

CREATE TABLE USERS(
    sales_id VARCHAR(20) NOT NULL,
    user_type_id INT NOT NULL,
    name VARCHAR(50) NOT NULL,
    email VARCHAR(100),
    preferred_name VARCHAR(50) NOT NULL,
    CONSTRAINT PK_USERS PRIMARY KEY (sales_id),
    CONSTRAINT FK_USERS_USER_TYPES FOREIGN KEY (user_type_id) REFERENCES USER_TYPES (id)
);

CREATE TABLE AMENITY_TYPES(
    id INT AUTO_INCREMENT NOT NULL,
    name VARCHAR(30) NOT NULL,
    recommended_duration INT NOT NULL,
    max_duration INT NOT NULL,
    CONSTRAINT PK_AMENITY_TYPES PRIMARY KEY (id)
);

CREATE TABLE AMENITIES (
    id INT AUTO_INCREMENT NOT NULL,
    name VARCHAR(20) NOT NULL,
    amenity_type_id INT NOT NULL,
    description VARCHAR(100) NOT NULL,
    location VARCHAR(50) NOT NULL,
    CONSTRAINT PK_AMENITIES PRIMARY KEY (id),
    CONSTRAINT FK_AMENITIES_AMENITY_TYPES FOREIGN KEY (amenity_type_id) REFERENCES AMENITY_TYPES (id)
);

CREATE TABLE STATUS (
    id INT AUTO_INCREMENT NOT NULL,
    name VARCHAR(10) NOT NULL,
    CONSTRAINT PK_STATUS PRIMARY KEY (id)
);

CREATE TABLE RESERVATIONS (
    id INT AUTO_INCREMENT NOT NULL,
    confirmation_number VARCHAR(20) NOT NULL,
    amenity_id INT NOT NULL,
    user_id VARCHAR(20) NOT NULL,
    reservation_date date NOT NULL,
    start_time time NOT NULL,
    end_time time NOT NULL,
    status_id INT NOT NULL,
    CONSTRAINT PK_RESERVATIONS PRIMARY KEY (id),
    CONSTRAINT FK_RESERVATIONS_AMENITIES FOREIGN KEY (amenity_id) REFERENCES AMENITIES (id),
    CONSTRAINT FK_RESERVATIONS_USERID FOREIGN KEY (user_id) REFERENCES USERS (sales_id),
    CONSTRAINT FK_RESERVATIONS_STATUSID FOREIGN KEY (status_id) REFERENCES STATUS (id)
);

CREATE TABLE WAITLIST (
    id INT AUTO_INCREMENT NOT NULL,
    user_id VARCHAR(20) NOT NULL,
    amenity_type_id INT NOT NULL,
    reservation_date date NOT NULL,
    start_time time NOT NULL,
    end_time time NOT NULL,
    status_id INT NOT NULL,
    CONSTRAINT PK_WAITLIST PRIMARY KEY (id),
    CONSTRAINT FK_WAITLIST_USERS FOREIGN KEY (user_id) REFERENCES USERS (sales_id),
    CONSTRAINT FK_WAITLIST_AMENITY_TYPES FOREIGN KEY (amenity_type_id) REFERENCES AMENITY_TYPES (id),
    CONSTRAINT FK_WAITLIST_STATUS FOREIGN KEY (status_id) REFERENCES STATUS (id)
);






v2





CREATE TABLE USER_TYPES(
    id INT AUTO_INCREMENT NOT NULL,
    name VARCHAR(5) NOT NULL,
    CONSTRAINT PK_USER_TYPES PRIMARY KEY (id)
);

CREATE TABLE USERS(
    sales_id VARCHAR(20) NOT NULL,
    user_type_id INT NOT NULL,
    name VARCHAR(50) NOT NULL,
    email VARCHAR(100),
    preferred_name VARCHAR(50) NOT NULL,
    CONSTRAINT PK_USERS PRIMARY KEY (sales_id),
    CONSTRAINT FK_USERS_USER_TYPES FOREIGN KEY (user_type_id) REFERENCES USER_TYPES (id)
);

CREATE TABLE AMENITY_TYPES(
    id INT AUTO_INCREMENT NOT NULL,
    name VARCHAR(30) NOT NULL,
    recommended_duration INT NOT NULL,
    max_duration INT NOT NULL,
    CONSTRAINT PK_AMENITY_TYPES PRIMARY KEY (id)
);

CREATE TABLE AMENITIES (
    id INT AUTO_INCREMENT NOT NULL,
    name VARCHAR(20) NOT NULL,
    amenity_type_id INT NOT NULL,
    description VARCHAR(100) NOT NULL,
    location VARCHAR(50) NOT NULL,
    CONSTRAINT PK_AMENITIES PRIMARY KEY (id),
    CONSTRAINT FK_AMENITIES_AMENITY_TYPES FOREIGN KEY (amenity_type_id) REFERENCES AMENITY_TYPES (id)
);

CREATE TABLE STATUS (
    id INT AUTO_INCREMENT NOT NULL,
    name VARCHAR(10) NOT NULL,
    CONSTRAINT PK_STATUS PRIMARY KEY (id)
);

CREATE TABLE RESERVATIONS (
    id INT AUTO_INCREMENT NOT NULL,
    confirmation_number VARCHAR(20) NOT NULL,
    amenity_id INT NOT NULL,
    user_id VARCHAR(20) NOT NULL,
    reservation_date date NOT NULL,
    start_time time NOT NULL,
    end_time time NOT NULL,
    status_id INT NOT NULL,
    CONSTRAINT PK_RESERVATIONS PRIMARY KEY (id),
    CONSTRAINT FK_RESERVATIONS_AMENITIES FOREIGN KEY (amenity_id) REFERENCES AMENITIES (id),
    CONSTRAINT FK_RESERVATIONS_USERID FOREIGN KEY (user_id) REFERENCES USERS (sales_id),
    CONSTRAINT FK_RESERVATIONS_STATUSID FOREIGN KEY (status_id) REFERENCES STATUS (id)
);

CREATE TABLE WAITLIST (
    id INT AUTO_INCREMENT NOT NULL,
    user_id VARCHAR(20) NOT NULL,
    amenity_type_id INT NOT NULL,
    reservation_date date NOT NULL,
    start_time time NOT NULL,
    end_time time NOT NULL,
    status_id INT NOT NULL,
    CONSTRAINT PK_WAITLIST PRIMARY KEY (id),
    CONSTRAINT FK_WAITLIST_USERS FOREIGN KEY (user_id) REFERENCES USERS (sales_id),
    CONSTRAINT FK_WAITLIST_AMENITY_TYPES FOREIGN KEY (amenity_type_id) REFERENCES AMENITY_TYPES (id),
    CONSTRAINT FK_WAITLIST_STATUS FOREIGN KEY (status_id) REFERENCES STATUS (id)
);
